### ISSUE TITLE
Display resolution settings during install

### ISSUE THREAD

**Issue by ChooChooAl** [linuxmint/mint20.1-beta#10]
I installed this Beta in Virtualbox 6.1 in Linux mint 10 cinnamon.
There is a horrible lack of 16:9 resolutions to pick from during live-cd test or after install.   Once Virtualbox guest additions was added I got more. The one 1360x768, which by the way is not 16:9 but something off as 1366x768 is 16:9, is about the only choice for my laptop display.
I'm looking for 1920x1080 to 1600x900 as possible options at least.  Much larger as they may work for others would be way to much for my eyes.

**Comment by clefebvre** [comment]
That's upstream from us. I don't think Virtualbox will care about it though. For anything serious you are recommended to install the Guest Additions, without them you're not supposed to expect anything much really.

On our side we bump the resolution to 1024x768 (it defaults to a ridiculous 800x600 otherwise), and that's about it.
