### ISSUE TITLE
eid - additionnal repositories not available for Ulyssa

### ISSUE THREAD

**Issue by MichelHanzen** [linuxmint/mint20.1-beta#15]
https://eid.belgium.be/en/linux-eid-software-installation
I tried to follow the installation procedure above. After step 1, eID-archive package installation, the additional repositories were not correct probably because a specific repository for ulyssa does not exist. So I could not proceed to step 2.
I had to remove the two repositories proposed and specify the one for Ulyana:
deb http://files2.eid.belgium.be/debian ulyana main
deb http://files.eid.belgium.be/debian ulyana main
After that, I can proceed to step 2

**Comment by MenthaSuaveolens** [comment]
Hi Michel,
The eid-software isn't supported yet for LM20.1. However, you can install the .deb-package and install the middle-ware only (sudo apt install eid-mw). After installing the middle-ware the extension for firefox is installed and one can use the eid-card to log in. The eid-viewer can't be installed due to some dependency-problems. The developers of the eid-software are always waiting to update their packages after the release of Ubuntu, Linux Mint. For that reason I'm always waiting to install a new release of LM until the eid-software has been released too (takes approx. 2 weeks). So this not a LM20.1-issue that the LM-developpers can tackle.
![SupportedDistros](https://user-images.githubusercontent.com/47174957/102605355-722bca80-4125-11eb-868e-1348c3a3a568.png)
