### ISSUE TITLE
mint-y-icons: Improve fcitx keyboard icon

### ISSUE THREAD

**Issue by janos-r** [linuxmint/mint20.1-beta#44]
I did a quick install of the beta in virtualBox.
Installed the Japanese input method packages. Set fcitx as the method. Restarted.
The icon is broken:
![image](https://user-images.githubusercontent.com/30606201/102877546-3788a180-4447-11eb-9f7b-61b260281a09.png)
This can be fixed for the default 24px size with: 
`sudo cp /usr/share/icons/hicolor/24×24/apps/fcitx-kbd.png /usr/share/icons/Mint-Y/devices/24/input-keyboard.png`
resulting in:
![image](https://user-images.githubusercontent.com/30606201/102880238-4a9d7080-444b-11eb-9582-84ebabb9da6b.png)

This was shortly discussed in:
https://github.com/linuxmint/cinnamon/commit/fa11b3f4bef8368f1fe020596035ed1f3dd6f959
And decided that on the mint side, the default icon should be updated.

Please try to fix this for 20.1. Mint has one of the best input method setups thanks to your 19.3 update, please don't tarnish this with a broken keyboard icon. I expected this to be done in 20.1 so I can recommend it to Japanese user, and any Asian users for that matter, since fcitx is the most used input method.

Thank you
Radim

**Comment by clefebvre** [comment]
ありがとう！I use it as well myself. This looks like an easy fix in mint-y-icons, thank you for reporting it.

**Comment by clefebvre** [comment]
Ok this isn't that simple after all... some apps use input-keyboard, and they do need to use an icon which looks like an app icon. Here's a list:

- virtual keyboard (in Cinnamon)
- keyboard preferences (in MATE)

If we add input-keyboard in mint-y-icons it might override the app icon. It might depend on the size of the icon though, but it's messy. It would be much better if fcitx was to use a better icon name.

I'll test and I'll check the fcitx code as well, it might be easier to just patch it.

**Comment by janos-r** [comment]
Mr Webster raised this issue with fcitx back when I first reported it and there was a brief discussion about the fcitx responsibility for the name here: https://github.com/fcitx/fcitx/issues/465
Unfortunately I don't see the backend complications that lead to this becoming an issue. But I hope it can be resolved.
いつもありがとう 🙏️

**Comment by clefebvre** [comment]
It could be argued that the two apps (in MATE and Cinnamon) should use a different icon name, but so should fcitx. The fact that they use a generic name is what the issue is here.. because it prevents the icon theme from making them look the way it wants. One same icon name can't look both like an app and like a device or a status icon.

anyway, if I patch fcitx to use fcitx-kbd instead of input-keyboard, I get this:

![image](https://user-images.githubusercontent.com/1138515/102902303-b9d48e00-4466-11eb-8c02-aeed6ce06173.png)

Does this look OK?

**Comment by janos-r** [comment]
Yes, that looks just like my my initial scrnshot from my hack with
`sudo cp /usr/share/icons/hicolor/24×24/apps/fcitx-kbd.png /usr/share/icons/Mint-Y/devices/24/input-keyboard.png`
To be honest, anything looking like a keybord would be sufficient, but the fcitx-kbd.png seams like a natural and good choice for fcitx.
Thank you very much for your trouble. And happy holidays 🎄️

**Comment by clefebvre** [comment]
Ok, so I see two possibilities:

The first possibility is to simply patch fcitx to use fcitx-kbd.

The second possibility is to:

- Remove input-keyboard from mint-y-icons
- Add a cs-app-virtual-keyboard icon in Cinnamon and use that for the virtual keyboard menu item
- Add a cs-app-virtual-keyboard in mint-y-icons

MATE will end up using a fallback, but it already does that in other apps anyway... (mouse prefs etc etc..).

**Comment by clefebvre** [comment]
The second possibility is the right thing to do. It's more tedious but all three projects are at fault here:

- Cinnamon
- MATE
- Fcitx

The least we can do is fix Cinnamon to make it use a specific name, and stop themeing the generic icon input-keyboard in mint-y-icons since it's used all over the place by completely different apps in completely different places.

**Comment by NikoKrause** [comment]
input-keyboard is not an app icon it's a device icon

https://github.com/linuxmint/mint-y-icons/blob/master/usr/share/icons/Mint-Y/devices/64/input-keyboard.png

**Comment by clefebvre** [comment]
I know Niko, it's a device icon which is trying to look like a device, like an app and like a status icon... and it's failing miserably :)

**Comment by NikoKrause** [comment]
Isn't this a general problem for apps, which use generic icon names? Iirc Back in Time also uses a generic icon, which makes it impossible to theme.

**Comment by clefebvre** [comment]
OK here we go:

- Cinnamon virtual keyboard moves from input-keyboard to new cinnamon-virtual-keyboard (mint-x based): https://github.com/linuxmint/cinnamon/commit/41e609565643759d2abf6b769d3580877d898580
- Mint-Y: input-keyboard icon removed https://github.com/linuxmint/mint-y-icons/commit/d0dc549673e158bef29a15faca5c6c00cb8aca61
- Mint-Y: new cinnamon-virtual-keyboard icon: https://github.com/linuxmint/mint-y-icons/commit/5bef774297d887a46498c564cde9c8a8e2a7c1ef

**Comment by clefebvre** [comment]
Yes, it can look good, it can look "OK", it can look horrible.. it really depends on the icon theme. In some icon themes apps don't have a surrounding shape and don't look different than status or device icons, so in these cases that looks OK.

The ideal case is when the app uses an icon name which no other app uses, and even better, when it uses a specific name for its status icon names, notifications, windows etc.. it's more work for the theme to properly support, but it always works (because the app provides the fallback icons in the hicolor theme), and when themes finally support it, it looks perfect.

Only the app properly knows the context and only the theme properly knows what each context must look like, so there's other good solution than good specific icon names.

**Comment by clefebvre** [comment]
OK so now it looks like this:

![image](https://user-images.githubusercontent.com/1138515/102920559-da124600-4482-11eb-8286-c350fa160ad8.png)

It uses input-keyboard from Adwaita/gnome basically...

@janos-r is that OK? It doesn't look great imo.

**Comment by clefebvre** [comment]
Shall we also patch fcitx to make it use fcitx-kbd and improve fcitx-kbd in mint-y-icons?

**Comment by janos-r** [comment]
Ah, I remember this icon. You get it even now when switching the icon theme to Adwaita, tough I couldn't find it's source in /usr/share/icons/Adwaita/
It is an unfortunate icon, It looks like a ironing iron. But well, it's better than the current white square.
Of course it would be better to have something more fitting. Of course the fcitx-kbd would be probably best. Or In Adwaita, the input-keyboard-symbolic could be more fitting as a generic systray icon.
![input-keyboard-symbolic symbolic](https://user-images.githubusercontent.com/30606201/102924717-65df9e80-4492-11eb-918f-233b7fcfd957.png) <- if it would have the proper color (white on black / black on white).
Either way, even if we are left with the iron, it's still better than a totally wrong icon. If we could have the original fcitx-kbd or at least the symbolic adwaita as the general mint-y icon, that would be best.

**Comment by clefebvre** [comment]
fcitx-kbd-symbolic actually looks better than Adwaita's input-keyboard-symbolic

![image](https://user-images.githubusercontent.com/1138515/102934819-cf64aa80-449c-11eb-8c24-b4277b767096.png)

We're testing XApp in MATE and Xfce to see if switching from symbolic kbd to fullcolor mozc re-sorts the icons and changes their position. If it doesn't, then we'll patch fcitx to use fcitx-kbd-symbolic.

**Comment by clefebvre** [comment]
Alright, so we need the following done:

- [x] Adjust MATE launchers to not use input-keyboard
- [x] Update Mint-Y with new cinnamon-virtual-keyboard and no input-keyboard
- [x] Update Cinnamon to use cinnamon-virtual-keyboard
- [x] Patch Fcitx to use fcitx-kbd-symbolic

**Comment by clefebvre** [comment]
All done. Thanks and good job everyone.
