### ISSUE TITLE
favorites: Nemo crashes if favorite has been removed outside Nemo

### ISSUE THREAD

**Issue by MenthaSuaveolens** [linuxmint/mint20.1-beta#54]
Applied all updates to LM 20.1
![NemoCrash](https://user-images.githubusercontent.com/47174957/103149200-a592d880-4767-11eb-9ba2-d115c12d0c24.png)
[NemoCrash.txt](https://github.com/linuxmint/mint20.1-beta/files/5742903/NemoCrash.txt)

1. Create a file and make it a favorite
2. Open terminal and delete the file
3. Open favorite => delete file is still present in favorite
4. Remove from favorite => nemo crashes

**Comment by MenthaSuaveolens** [comment]
It is far fetched, but if you make by accident a favorite of a file on a remote instance and the instance is disconnected from the computer, then there is no way to remove the file from the favorites.

**Comment by clefebvre** [comment]
It should still be present (i.e. 3 is OK, by design).
the crash is obviously not ok though :)

**Comment by MenthaSuaveolens** [comment]
Indeed 3 is OK by design

**Comment by mtwebster** [comment]
The main issue of crashing should no longer occur. Missing files aren't automatically purged mainly because I thought i would be nice to be able to force mounting of a device or remote connection if the file was simply 'unavailable', and in Nemo that's what should happen if you try to open a favorite located on an unmounted filesystem.

This behavior doesn't work yet for the favorites applet and menus.

There are a few commits that contribute to fixing this crash as a side effect.
https://github.com/linuxmint/xapp/commit/12808ba6dd15d49deab0219bd14229a573f050d3
https://github.com/linuxmint/xapp/commit/05e5a4cc0418457e5a7107d617f2d33d418c044a
https://github.com/linuxmint/xapp/commit/4a0eb5577ff0926aa9432be71a0eee74488c2296
