### ISSUE TITLE
mintreport: No crash reports showing up in the system reports, even after several hard crashes.

### ISSUE THREAD

**Issue by crhy** [linuxmint/mint20.1-beta#72]

**Comment by Acheron17** [comment]
I have wondered about this myself.  Was there an upstream change in a problem reporting package?  It seems that a discrete coredump file is not created in '/var/log/' anymore and is instead recorded in the journald log file.

**Comment by clefebvre** [comment]
Run `mintreport` from the command line to see if you see any errors.

Also run `coredumpctl` to see what it says.

**Comment by Acheron17** [comment]
harry@front-office:~$ mintreport
harry@front-office:~$ Checking 045_xappstatusapplet-missing
/usr/lib/linuxmint/mintreport/app.py:200: DeprecationWarning: Gtk.ImageMenuItem.set_image is deprecated
  item.set_image(image)
Checking 050_install-media-codecs
Checking 060_timeshift-no-setup
Checking 070_new-release
Checking 071_new_major_release
Checking 080_release-eol
Checking 200_xappstatusapplet-blocked
Checking 500_install-language-packs
Checking 900_drivers
Ignoring driver: {'free': True, 'builtin': True, 'from_distro': True, 'recommended': False} (builtin)

List of crash Crash Reports are empty.

However ...

harry@front-office:~$ coredumpctl
TIME                            PID   UID   GID SIG COREFILE  EXE
Wed 2020-12-16 18:04:34 EST    1339  1000  1000   5 missing   /usr/libexec/csd->
Thu 2020-12-17 04:24:29 EST    9874  1000  1000  11 missing   /usr/bin/python3.8
Thu 2020-12-17 05:23:57 EST   10708  1000  1000  11 missing   /usr/bin/python3.8
Thu 2020-12-24 16:07:47 EST    4468  1000  1000  11 missing   /usr/bin/python3.8
Thu 2020-12-24 16:17:13 EST    3155  1000  1000  11 missing   /usr/bin/python3.8
Thu 2020-12-24 16:24:39 EST    4755  1000  1000  11 missing   /usr/bin/python3.8
Thu 2020-12-24 16:37:43 EST    5388  1000  1000  11 missing   /usr/bin/python3.8
Thu 2020-12-24 16:50:28 EST    6379  1000  1000  11 missing   /usr/bin/python3.8
Thu 2020-12-24 16:52:21 EST    6518  1000  1000  11 missing   /usr/bin/python3.8
Thu 2020-12-24 17:32:46 EST    6825  1000  1000  11 missing   /usr/bin/python3.8
Fri 2020-12-25 04:48:39 EST   16505  1000  1000  11 missing   /usr/bin/python3.8
Fri 2020-12-25 12:52:04 EST   20596  1000  1000  11 missing   /usr/bin/python3.8
Fri 2020-12-25 13:22:11 EST   28295  1000  1000  11 missing   /usr/bin/python3.8
Sat 2020-12-26 14:38:52 EST   45876  1000  1000  11 missing   /usr/bin/python3.8
Sat 2020-12-26 14:40:21 EST   46047  1000  1000  11 missing   /usr/bin/python3.8
Sun 2020-12-27 07:26:07 EST   54711  1000  1000  11 truncated /usr/bin/python3.8
Mon 2020-12-28 08:55:02 EST   79907  1000  1000  11 present   /usr/bin/python3.8

**Comment by clefebvre** [comment]
Python crashes are ignored by design, they can be the result of simple exceptions.

https://github.com/linuxmint/mintreport/blob/7b7d7ed105d0e7f3dd494415f127e9ab81bb2e75/usr/lib/linuxmint/mintreport/app.py#L443

"missing" means the core is no longer available.. mintreport will ignore that as well. That's by design also.

To make sure a crash is properly registered you can try to make Cinnamon crash on purpose (Alt+F2 -> lg -> Actions -> Crash Cinnamon). It should then have an entry in coredumpctl and in mintreport.

**Comment by Acheron17** [comment]
Confirming that per your instructions to crash Cinnamon, an entry was in coredumpctl and in mintreport.

**Comment by clefebvre** [comment]
Excellent. Thanks for your help @Harry-W-Haines-III .

**Comment by crhy** [comment]
coredumpctl:  No coredumps found.  mintreport works without issue.  Several more hard crashes, and still didn't get any crash reports.  I ran the updates as of today.

**Comment by crhy** [comment]
Again, why is this closed?  I'm not sure I understand the process here.  Bug still exist:  Report closed?  Why?  This is reproducible.  I just reproduced it (after running all updates).

**Comment by clefebvre** [comment]
It's closed because there's nothing left to do. You observe the fact that it doesn't work for you but you don't know why. We observe the fact that it works well for us and we don't see anything out of the ordinary.. it picks up crashes, ignores missing ones and python ones. There's no actual bug, just observations.

Closing an issue doesn't mean we're doubting your observation. It means we're done working on the issue. If we don't know why something fails and we can't reproduce it, we've nothing to fix.

**Comment by crhy** [comment]
These continued crashes should be reported though.  So I think there is definitely an issue with the crash report tool.  Just FYI.
![20210103_125148](https://user-images.githubusercontent.com/21183395/103490921-3ea69c80-4dc3-11eb-9df1-3df332a84b51.jpg)
