### ISSUE TITLE
Nemo: 'Favorites' files in the left panel are missing a preview for graphics files

### ISSUE THREAD

**Issue by Acheron17** [linuxmint/mint20.1-beta#8]
'Favorites' files in the left panel are missing a preview for graphics files, jpg, png, gif, tif in the right panel.  This might not be a bug but more of a feature request if the corresponding thumbnail file is not generated in ~/.cache/thumbnails.

in the dconf file: root-metadata=['string==metadata::show-thumbnails==true']

![Screenshot-from-2020-12-16-12-25-03](https://user-images.githubusercontent.com/45599505/102383871-0832ea00-3f9a-11eb-8830-9bebad5e18f8.png)

**Comment by mtwebster** [comment]
Where are these files actually located? Are they on your local disk or on some remote location (sftp or smb, etc..)?

What is your edit->preferences->preview->show thumbnails set to?

If you visit the actual location of the files do their thumbnails appear?

**Comment by Acheron17** [comment]
![Screenshot-from-2020-12-17-10-17-17](https://user-images.githubusercontent.com/45599505/102506465-1c85ee00-4051-11eb-9f66-29000ec7c8ca.png)

These files are located on a local disk.

Show thumbnails: [Local Files Only], Inherit thumbnail visibility from parent [unchecked]

If you visit the actual location of the files do their thumbnails appear? [Yes]  Also seeing the same thing with PDFs.

Just an additional note.  I thought there might be something wrong with my install as I install additional applications.  I went back to a live USB and was able to repeat the issue.

**Comment by Acheron17** [comment]
Is there anything further I can do assist with this?  Here are screen shots of Recent and Favorites with same files showing the difference.

![recent](https://user-images.githubusercontent.com/45599505/103090345-c9ff8100-45be-11eb-9e74-a183a047957b.png)
![favorites](https://user-images.githubusercontent.com/45599505/103090356-cd930800-45be-11eb-8220-d88a0b78637a.png)

**Comment by mtwebster** [comment]
Hi, I think I've got this taken care of:
https://github.com/linuxmint/xapp/commit/ddf029cbea5d1419bc7214f76220baebbc256b91
https://github.com/linuxmint/nemo/commit/b27c141acbda65255e464e6e69be84e7b2ce1a39

Favorites is a virtual folder and those are not considered 'local' normally (and the parent folder is used to decide whether to show thumbnails). But since these files are really in other, local folders, favorite files will now be considered local if their 'target' file is local.

As a workaround, you could go into preferences and set 'show thumbnails' to yes (instead of local-only). This worked for me in a clean install. Once there's a new release with these fixes (and others) then the favorites view should show thumbnails for local files by default.

**Comment by Acheron17** [comment]
Setting 'show thumbnails' to yes worked for me.  Previews are now shown in the right panel.

**Comment by Acheron17** [comment]
I just did the updates today and the issue still persists.  I had set  'show thumbnails'  to 'local only' waiting for the fix.  Had to set back to 'Yes' to get the preview to show up.  I deleted all the favorites and created new ones just to make sure that wasn't causing the issue.

**Comment by mtwebster** [comment]
Can you try the following:
```
gsettings reset-recursively org.x.apps.favorites
rm -rf ~/.cache/thumbnails
sudo killall nemo
nemo
```
And then re-create the favorites.

The one issue I still notice is if the file isn't thumbnailed already in its own folder, it won't show one in favorites:/// - I'll have another look at that, but otherwise it seems to work fine.

1) Go find some images and right-click - make them favorites (they are thumbnailed at this point)
2) Go to the favorites "folder" and the files have thumbnails.

**Comment by Acheron17** [comment]
That fixed it!  I see now, had to do some things to make it seem like a clean install.  Thanks !!
